---
abstract: 'use Test::Able without a bunch of boilerplate'
author:
  - 'Andrew Sterling Hanenkamp'
generated_by: 'Dist::Zilla version 1.100130'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Able-Runner
requires:
  ExtUtils::MakeMaker: 6.11
  Module::Pluggable: 3.6
  Moose: 0.94
  Test::Able: 0.09
version: 1.000
